"""Per-company evidence reports.

This is the artifact to open when a judge asks where a number came from. For each
metric it shows the final figure, the arithmetic that produced it, every candidate
estimate with its weight, the source quotes with document paths, and what the
validation gate found.
"""

from __future__ import annotations

from pathlib import Path

from avws.config import RESEARCH_DIR
from avws.estimators.base import Estimate
from avws.ledger import Fact
from avws.registry import metrics_for


def write_report(
    ticker: str,
    estimates: dict[str, Estimate],
    candidates: dict[str, list[Estimate]],
    facts_by_metric: dict[str, list[Fact]],
    findings: dict[str, list[str]],
    identity_issues: list[str],
) -> Path:
    metrics = metrics_for(ticker)
    company = metrics[0].company
    lines: list[str] = [
        f"# {company} ({ticker}) - {metrics[0].period}",
        "",
        "Generated by the JustAsh forecasting agent. Every figure below traces to a",
        "quoted passage in the frozen document corpus.",
        "",
        "## Forecast summary",
        "",
        "| Metric | Units | Forecast | Method |",
        "| --- | --- | ---: | --- |",
    ]
    for metric in metrics:
        est = estimates[metric.label]
        lines.append(
            f"| {metric.label} | {metric.units} | {est.value:,.4g} | {est.method} |"
        )

    lines += ["", "## Cross-metric identity checks", ""]
    if identity_issues:
        lines += [f"- {issue}" for issue in identity_issues]
    else:
        lines.append("- No violations found.")

    for metric in metrics:
        est = estimates[metric.label]
        lines += [
            "",
            "---",
            "",
            f"## {metric.label} ({metric.units})",
            "",
            f"**Forecast: {est.value:,.6g} {metric.units}**",
            "",
            "### Derivation",
            "",
            "```",
            est.derivation,
            "```",
            "",
            "### Candidate estimates",
            "",
            "| Method | Value | Confidence | Note |",
            "| --- | ---: | ---: | --- |",
        ]
        for candidate in candidates.get(metric.label, []):
            note = "; ".join(candidate.warnings) if candidate.warnings else ""
            lines.append(
                f"| {candidate.method} | {candidate.value:,.6g} | "
                f"{candidate.confidence:.2f} | {note} |"
            )

        lines += ["", "### Validation gate", ""]
        for finding in findings.get(metric.label, []) or ["- (no findings recorded)"]:
            lines.append(f"- {finding}")

        facts = facts_by_metric.get(metric.key, [])
        lines += ["", f"### Evidence ({len(facts)} facts extracted)", ""]
        if not facts:
            lines.append("No facts were extracted for this metric.")
        for fact in sorted(facts, key=lambda f: (f.basis, f.period))[:20]:
            lines.append(
                f"- **{fact.basis}** `{fact.period}` **{fact.value:,.6g}** "
                f"{fact.unit} - \"{fact.source_quote[:200]}\"  \n"
                f"  source: `{fact.source_doc}`"
            )

    RESEARCH_DIR.mkdir(parents=True, exist_ok=True)
    path = RESEARCH_DIR / f"{ticker}.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
